test:
  script:
  - doxygen doxygen/Doxyfile
  except:
  - master
  
pages:
  script:
  - doxygen doxygen/Doxyfile
  - mv documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
