test:
  script:
  - doxygen doxygen/Doxyfile
  except:
  - master
  
pages:
  script:
  - line=$(cat CMakeLists.txt | grep "project(.*)" -o); tmp=${line:8}; proj_name=${tmp:0:${#tmp}-1}; sed -i 's/\(PROJECT_NAME\s*=\s*\)\".*\"/\1\"'$proj_name'\"/g' Doxyfile Doxyfile;
  - doxygen Doxyfile
  - mv doc/html/ ~/public_artifacts
  artifacts:
    paths:
    - doc
  only:
  - master
